name: PullRequestAction

on:
  pull_request_target:
    branches: [ main, master ]
    paths-ignore:
      - .github/workflows/push.yml

jobs:
  build:
    runs-on: [ self-hosted, containers-runner ]
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: container-repo

      - name: Merge test branch
        uses: linaro-its/merge-test-branch@v2.6
        with:
          path: container-repo

      - name: Determine image tag
        run: |
          IMAGE_TAG=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - run: env

      - run: cat $GITHUB_EVENT_PATH

      - name: Build container image
        run: |
          cd $GITHUB_WORKSPACE/container-repo
          # Do some magic to figure out what our base image is
          IFS=' ' read -ra FOO <<< $(grep "FROM" Dockerfile)
          # Make sure we have the latest Ubuntu base image
          docker pull ${FOO[1]}
          # and then build our container.
          docker build --force-rm -t "linaroits/jekyllsitebuild:$IMAGE_TAG" .

  test:
    runs-on: [ self-hosted, containers-runner ]
    needs: build
    strategy:
      matrix:
        site: [96boards-ai, 96boards-docs, 96boards-org, connect,
               devicetree, linaro-cloud, linaro-org, lkft,
               morello, mlplatform, op-tee, openamp,
               trustedfirmware]
        include:
          - site: 96boards-ai
            repo: 96Boards/ai
          - site: 96boards-docs
            repo: 96Boards/documentation
          - site: 96boards-org
            repo: 96Boards/website
          - site: connect
            repo: Linaro/Connect
          - site: devicetree
            repo: devicetree-org/devicetree-website
          - site: linaro-cloud
            repo: Linaro/cloud
          - site: linaro-org
            repo: Linaro/website
          - site: lkft
            repo: Linaro/lkft-website
          - site: morello
            repo: MorelloProject/website
          - site: mlplatform
            repo: ArmNNWebsite/website
          - site: op-tee
            repo: OP-TEE/optee_website
          - site: openamp
            repo: OpenAMP/website
          - site: trustedfirmware
            repo: TrustedFirmwareWebsite/website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ matrix.site }}
          repository: ${{ matrix.repo }}

      - name: Initialise environment
        run: cat "$GITHUB_WORKSPACE/${{ matrix.site }}/.github-env-master" >> $GITHUB_ENV

      - name: Determine image tag
        run: |
          IMAGE_TAG=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Directory push/pop
        uses: linaro-its/directory-push-and-pop@v2.4
        with:
          cacheDirectory: /srv/site-builds
          namedDirectory: ${{ env.SITE_URL }}
          destinationDirectory: ${{ github.workspace }}/${{ matrix.site }}
          popAtEnd: false

      - name: Build site
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.site }}
          JEKYLLSITEBUILD=$IMAGE_TAG ./build-site.sh

  finally:
    runs-on: [ self-hosted, containers-runner ]
    needs:
      - build
      - test
    if: "always()&&(needs.build.result=='success')"
    steps:
      - name: Determine image tag
        run: |
          IMAGE_TAG=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Remove test Docker image
        run: docker rmi linaroits/jekyllsitebuild:$IMAGE_TAG
